name: linting
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linting:
    name: "linting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: linting
        shell: pwsh
        run: |
          ./entrypoint.ps1 lint
