name: Versioned
on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Release
        shell: pwsh
        run: |
          ./Build.ps1 -Stages Build,Test,Upload,Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: docker.pkg.github.com
          DOCKER_BASEPATH: ${{ github.repository }}
          DOCKER_TAGS: "latest"
