name: Versioned
on:
  push:
    tags:
      - "v*"

jobs:
  BuildPSCore:
    name: "Powershell Core on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        shell: pwsh
        run: |
          ./Build.ps1 -Stages Build,Test

  BuildPSDesktop:
    name: "Powershell Desktop on windows-latest"
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        shell: powershell
        run: |
          ./Build.ps1 -Stages Build,Test

  Linting:
    name: "Linting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Super Linter"
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Publish:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: [BuildPSCore, BuildPSDesktop, Linting]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Publish
        shell: pwsh
        run: |
          ./Build.ps1 -Stages Build,Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
