name: Versioned
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Publish
        shell: pwsh
        run: |
          ./Build.ps1 -Stages Build,Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
